[package]
name = "banscii-pl011-driver"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
banscii-pl011-driver-interface-types = { path = "./interface-types", version = "0.1.0" }
heapless = "0.7.16"
sel4cp = { path = "../../../../../sel4cp", version = "0.1.0", default-features = false }
tock-registers = "0.8.1"
