[package]
name = "sel4cp-hello"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
sel4cp = { path = "../../../../../sel4cp", version = "0.1.0" }
