[package]
name = "sel4-config-generic-macro-impls"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
fallible-iterator = "0.2.0"
proc-macro2 = "1.0.50"
quote = "1.0.23"
sel4-config-generic-types = { path = "../types", version = "0.1.0" }
syn = { version = "1.0.107", features = ["full"] }
