[package]
name = "sel4-simple-task-threading"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
alloc = []

[dependencies]
sel4 = { path = "../../../../sel4", version = "0.1.0" }
sel4-panicking = { path = "../../../../sel4-panicking", version = "0.1.0" }
