FROM nixos/nix:latest
# FROM nixos/nix:2.19.0

# COPY setup.sh /tmp

# RUN nix-env -iA nixpkgs.bash-completion
# RUN nix-env -iA nixpkgs.nix-bash-completions

# RUN set -eux; \
#     echo ". ~/.nix-profile/etc/profile.d/nix.sh" >> ~/.bashrc ; \
#     echo ". ~/.nix-profile/etc/profile.d/bash_completion.sh" >> ~/.bashrc; \
#     true

RUN rm -r /etc/nix /etc/ssl

WORKDIR /work/hacking/docker
